[package]
name = "teamech-console"
version = "0.6.1"
authors = ["ellie"]

[dependencies]
tiny-keccak = "1.4.2"
rand = "0.3"
pancurses = "0.16"
dirs = "1.0.3"
clap = "2.32"
chrono = "0.4"
byteorder = "1"
